### PR TITLE
Fixed README launch example by adding BOT_TOKEN

### PR DESCRIPTION
**Pull request by iWhiver**
Corrected the very first example in the README so that new users are not scared by the compilation error

### CODE REVIEW

**Comment by iWhiver** [comment]
Before

INFO:Client:Authorization process has been started with phone
INFO:Client:Sending encryption key
INFO:Client:Setting up option disable_persistent_network_statistics = True
INFO:Client:Setting up option disable_sent_scheduled_message_notifications = True
Traceback (most recent call last):
  File "/Users/{user}/PycharmProjects/aiotdlib/main.py", line 25, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/{user}/PycharmProjects/aiotdlib/main.py", line 18, in main
    async with client:
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/client.py", line 611, in __aenter__
    return await self.start()
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/client.py", line 1064, in start
    await self.authorize()
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/client.py", line 1033, in authorize
    result = await next_action()
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/client.py", line 819, in _check_database_encryption_key
    await self._setup_options()
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/client.py", line 783, in _setup_options
    await self.api.set_option(k, option_value, skip_validation=True)
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/api/api.py", line 17698, in set_option
    return await self.client.request(
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/client.py", line 964, in request
    await pending_request.wait(raise_exc=True, timeout=request_timeout)
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/utils.py", line 110, in wait
    self.raise_error()
  File "/Users/{user}/PycharmProjects/aiotdlib/aiotdlib/utils.py", line 122, in raise_error
    raise http_error(
TypeError: BadRequest.__init__() got an unexpected keyword argument 'code'

**Comment by pylakey** [comment]
Your changes are not related to this issue

**Comment by iWhiver** [comment]
> Your changes are not related to this issue

Well, what is the best way to solve this problem?

**Comment by pylakey** [comment]
Please provide minimal working code example which can help to reproduces this issue

**Comment by iWhiver** [comment]
> Please provide minimal working code example which can help to reproduces this issue

Sorry for the inconvenience, tried to replay the problem with a fresh build, everything works

**Pull request closed without merging**
